#!/bin/zsh

if hash "vim" 2>/dev/null; then
  if [ ! -d ~/.vim/bundle/Vundle.vim ]; then
    mkdir -p /.vim/bundle/
    git clone -q https://github.com/gmarik/Vundle.vim.git ~/.vim/bundle/Vundle.vim
    vim +PluginInstall +qall
  fi
fi
