#!/usr/bin/env ksh

if [ $(whence -p vim) ]; then
  if [ ! -d ~/.vim/bundle/Vundle.vim ]; then
    mkdir -p /.vim/bundle/ > /dev/null 2>&1
    git clone -q https://github.com/gmarik/Vundle.vim.git ~/.vim/bundle/Vundle.vim
    vim +PluginInstall +qall
  fi
fi
